### ISSUE TITLE
numpy missing attribute

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#101]
@Eric89GXL `calc_median_hp` is throwing an attribute error re: `trace` which appears to be a `numpy` rather than a `numpy.linalg` attribute. Can you confirm [this](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.trace.html) is not what you want. cc @mdclarke.

**Comment by kambysese** [comment]
@Eric89GXL I am not sure what `trace` is doing but if checking to see if `m` is special-orthogonal i.e., rotaional then wouldn't we want to do:
(1) `assert_allclose(np.dot(m, m.T), np.eye(3), atol=1e-5)` 
(2) `assert_allclose(np.linalg.det(m), 1., atol=1e-5)` #for the determinant

**Comment by Eric89GXL** [comment]
I think I might have tried something similar and had problems, but maybe I
had a formula wrong. I agree yours is more complete so let's give it a
shot. The trace is just sum of diagonal which is a less complete check.
