### ISSUE TITLE
Tranformation matrices identical

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#108]
@mdclarke Came upon this curious happening where `show_fiff` returns identical hp transfoms & position for the raw fif file:
> show_fiff -vt 222 subj_01_funloc_raw.fif 
> 222 = transform      	device -> head
> 	0.999924 -0.011817 0.003415
> 	0.012023 0.997590 -0.068330
> 	-0.002599 0.068366 0.997657
> 	2.844225 -12.823307 53.634003 (inv. -2.550447 9.159262 -54.394264)

and the median hp file:
> show_fiff -vt 222 subj_01_median_pos.fif 
> 222 = transform      	device -> head
> 	0.999924 -0.011817 0.003415
> 	0.012023 0.997590 -0.068330
> 	-0.002599 0.068366 0.997657
> 	2.844225 -12.823307 53.634003 (inv. -2.550448 9.159266 -54.394272)

We thought this might be isolated to the two infant datasets Maggie was working with, but it is also the case with files from the example dataset (above). Are we sure mne-python is actually changing the transform matrix in the file `info` structure?

**Comment by Eric89GXL** [comment]
It's possible it does not, will check tomorrow

**Comment by Eric89GXL** [comment]
There is only one run for the example subject. Currently `mnefun` uses the median of the *initial head positions of each run* as opposed to the median *across all time points of all runs*. So it makes sense that it finds the median of the initial head positions to be the same as the one existing initial head pos. This is something we could improve at some point, though, to use the median across time.

**Comment by kambysese** [comment]
That is somewhat reassuring, I wasn't aware this was the case. Is it in the doc? This is obviously fine for adults but I suspect very problematic for children as movement away from from initial hp is the norm, DYT? is the median across time something that has to be done on the mne-python or mnefun end? I could give it a shot for the latter.

**Comment by Eric89GXL** [comment]
Hmmm... we could presumably put it in mne-python at some point, but mnefun might be a better start. I have code for doing time-weighted average head position here:

https://github.com/LABSN/larsoner/blob/master/movement/movement.py#L297

We should also add some sanity checks to the position calculation stuff, I've written a function here:

https://github.com/LABSN/larsoner/blob/master/movement/movement.py#L268

We probably don't want to throw an error if the movements are implausible, but we should emit a warning.

**Comment by kambysese** [comment]
Are these links private? Both return 404 page not found

**Comment by Eric89GXL** [comment]
Whoops, needed to add you as a collaborator. Should work now.
