### ISSUE TITLE
Issues on master

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#111]
@Eric89GXL I don't know what is happening on master but a lot of things seem to be broken e.g., how did [this](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L597) get reverted? I thought this was fixed [here](https://github.com/kambysese/mnefun/blob/median-hp/mnefun/_mnefun.py) and merged #102?

**Comment by Eric89GXL** [comment]
You can always look through the commit history to trace it:

https://github.com/LABSN/mnefun/commits/master

Working my way up from the merge that had the change, I found I did a bad rebase in one of my commits:

https://github.com/LABSN/mnefun/commit/202b1841cf23e5c60268219c534c27e969c9d543

But really you can get there sooner using the `blame` tab on GitHub while browsing the codebase:

https://github.com/LABSN/mnefun/blame/master/mnefun/_mnefun.py#L597

I'll push a commit to fix it.

**Comment by Eric89GXL** [comment]
Fixed:

https://github.com/LABSN/mnefun/commit/c154749ce44d923cc7b5357441e79fe095f87393

**Comment by kambysese** [comment]
These are things you actually see on your github page(s) commit history and `blame`. This is the first I am hearing of them! 

And speaking of rebasing I lost everything I did for the maxwell filtering bit trying to rebase. 

This is all just too much for my feeble mind to follow. Thanks for the fix.

**Comment by Eric89GXL** [comment]
There are creepy ways to get back what you did. I did a `reset --hard` followed by `push force` once on a branch I'd been working on for 2 weeks. Got it back with a few git commands. I can look for them if you want. But *don't delete the affected branch*.

**Comment by kambysese** [comment]
Too late. I was dizzy yesterday trying to keep track of commits, changes and branches etc yesterday,  I thought deleting (my entire .git folder) was the only way to TRY and get back to some sort of starting position.

**Comment by kambysese** [comment]
Just out of curiosity how would I find via one of the above routes the commit where I suspect you hard coded `params.tsss_dur=60.` and renamed the extra maxfilter argument(s) kwarg to `mf_args`? I could swear we discussed at some point giving the user the option to set tsss buffer length e.g., for infant data.

**Comment by kambysese** [comment]
@Eric89GXL I am not going to PR anything for a while. Everything is at a stand still for me right now. You got a syntax error in the commit above at [ln 608](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L608)

**Comment by Eric89GXL** [comment]
I'd use `git blame` to find changes related to `tsss_dur`, if it exists in `master`. If it's not there, we'd have to look up the git commands to find it in any previous commit. I'm sure there's a way to do it...

Syntax error fixed, sorry about that.
