### ISSUE TITLE
EEG ECG rejection

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#113]
@Eric89GXL rejection criterion for ECG SSP is at 50e-6 micro volts on [EEG](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L229) chs, this correct?

**Comment by Eric89GXL** [comment]
Hmm... probably done to exclude any segments that have residual EOG blink or other artifacts in them, so that only "clean" (other than ECG artifacts) data get processed. So if not intentional, at least justifiable...

**Comment by Eric89GXL** [comment]
But it looks like it probably wasn't that way before, so maybe we should make it 150 or something else. WDYT?

**Comment by kambysese** [comment]
The justification is reasonable concerning ECG projections; I suspect @ 150 we may risk contaminating ECG epochs with blink artifacts but as long as the projectors are faithful to the ECG I am fine with 50. Closing.
