### ISSUE TITLE
How to cite mnefun? Add to Zenodo?

### ISSUE THREAD

**Issue by ilogue** [LABSN/mnefun#114]
How do you suggest writing a reference for mnefun? Is there a comprehensive list of authors (full names)?
Maybe you could use Zenodo to create a DOI for the project.

**Comment by Eric89GXL** [comment]
So far I haven't felt it was necessary to cite it because it's mostly an organizational library, with all the heavy lifting algorithms implemented in mne-python. Would it suffice just to cite that?
