### ISSUE TITLE
DOC: int_order and ext_order mixup

### ISSUE THREAD

**Issue by Eric89GXL** [LABSN/mnefun#124]
From @staulu:

> I just noticed that there's a little mixup in your _mnefun.py file. The parameter listing says that the defaults for int_order and ext_order are 3 and 8, respectively. Should be the other way around. 

Whoever opens a PR next should fix this on the way.

**Comment by kambysese** [comment]
It's just a mistake in the `docstring`. I'll get to it tomorrow. cc @staulu see [here](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L353)
