### ISSUE TITLE
File fetching issue

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#127]
@Eric89GXL I encountered this yesterday  on Alexis' MBP

>  Traceback (most recent call last):
>    File "/Users/alexisbosseler/projects/social_exposure/analysis_social_exposure.py", line 50, in <module>
>      print_status=True
>    File "/Users/alexisbosseler/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 570, in do_processing
>      outs[ii] = func(p, subjects, run_indices)
>    File "/Users/alexisbosseler/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 624, in fetch_raw_files
>      move(op.join(raw_dir, fname), op.join(raw_dir, op.basename(fname)))
>    File "/Users/alexisbosseler/anaconda/lib/python2.7/shutil.py", line 302, in move
>      copy2(src, real_dst)
>    File "/Users/alexisbosseler/anaconda/lib/python2.7/shutil.py", line 130, in copy2
>      copyfile(src, dst)
>    File "/Users/alexisbosseler/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
>      with open(src, 'rb') as fsrc:
> IOError: [Errno 2] No such file or directory: u'/Users/alexisbosseler/Documents/social_exposure/adim_aaron/raw_fif/dim_aaron/raw_fif/adim_aaron_1_raw.fif'

I don't have much time to debug this at the moment, I was hoping you might have a idea where the failure is, or why? I am not sure why the routine is lopping off the first letter of the directory name(s) i.e., `adim_aaron` to `dim_aaron`, when trying to do housekeeping after fetching files from remote.

**Comment by Eric89GXL** [comment]
The easiest thing to do would be to use `import pdb; pdb.pm()` and traverse up `u` 3 (or 4?) levels so you can look at what's happening in `fetch_raw_files` with e.g. `p raw_dir`, `p fname`, and `p op.basename(fname)`

**Comment by kambysese** [comment]
You mean debugging :smirk:

**Comment by Eric89GXL** [comment]
Yeah, but the kind that won't take much time :)

**Comment by kambysese** [comment]
@Eric89GXL What exactly is the reasoning for this [line](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L603)? I don't understand why it mostly works and fails in this case by dropping one char from beginning of `fname`.

**Comment by Eric89GXL** [comment]
I think it's to trim off the trailing `/` from the filename, there is probably a cleaner/safer way to do it. Probably in one it's entered as `'directory/'` and in the other (failing one) it's entered as `'directory'`
