### ISSUE TITLE
chpi weighted averaging

### ISSUE THREAD

**Issue by jjnurminen** [LABSN/mnefun#137]
I guess you'd also want the cHPI weighted averager integrated into mnefun?

**Comment by Eric89GXL** [comment]
Yeah sure

**Comment by jjnurminen** [comment]
That thing should eventually use ElektaAverager from mne, so I'll submit a PR after ElektaAverager has been merged.

**Comment by kambysese** [comment]
Hi Jussi cc @jjnurminen I am trying to figure out how to use the [chpi weighted averaging](https://github.com/BioMag/meg_scripts/blob/master/python/chpi_weighted_average.py) with the hopes of helping to integrate the averager into mnefun. Some questions for you and @Eric89GXL:

1. What is fundamentally different between [elekta_avg](https://github.com/BioMag/meg_scripts/blob/master/python/elekta_avg.py) and `AcqParserFIF` in mne-python? 
2. For integration into mnefun I suspect only the functions in [chpi weighted averaging](https://github.com/BioMag/meg_scripts/blob/master/python/chpi_weighted_average.py) are necessary?
3. Related to 2, for most users integration into mnefun will require handling events coded using the [Expyfun](https://github.com/LABSN/expyfun) framework. As is, it seems the only way for this to happen is passing averaging dictionaries to the averager from events/conditions in mnefun `params` class?

**Comment by jjnurminen** [comment]
Hi @kambysese 
my plan is to integrate the weighted averager into mnefun. I'll try to work on it asap.

1. AcqParserFIF is more complete. elekta_avg is an early version of AcqParserFIF and does not support all DACQ features. I'm going to rewrite the weighted averager to use AcqParserFIF instead.
2. Yep, and elekta_avg (or rather AcqParserFIF)
3. I'm not familiar with Expyfun, but I think it should be feasible to convert the events/parameters into AcqParserFIF format.

**Comment by jjnurminen** [comment]
@kambysese there is now an updated version in https://github.com/BioMag/meg_scripts that uses AcqParserFIF. Some other enhancements as well (e.g. epoch rejection).
Integration into mnefun coming a bit later...

**Comment by kambysese** [comment]
@jjnurminen as per @staulu I am trying to run  `chpi_weighted_average` on a phantom dataset. Firstly, as `python chpi_weighted_average.py chpi_snr_test_raw_tsss_mc.fif` fails with a [`ValueError`](https://github.com/BioMag/meg_scripts/issues/2). After some tinkering I managed to produce chpi weighted averages with:

```
raw_fname = '/media/ktavabi/ALAYA/data/sandbox/chpi_snr_test_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, allow_maxshield="yes", preload=True)
raw_sss = mne.preprocessing.maxwell_filter(raw, origin=(0., 0., 0.), int_order=8,
                                           st_correlation=.98, st_duration=10,
                                           destination=None,
                                           coord_frame='meg', head_pos=None,
                                           regularize='in')  # no movement compensation
ap = AcqParserFIF(raw_sss.info)
cond = ap.get_condition(raw_sss, ap['Dipole 7'], stim_channel='STI201')
epochs = mne.Epochs(raw_sss, reject=None, flat=None, preload=True,  **cond)
w_snr = chpi_snr_epochs(epochs, channels='grad', hpi_coil='median')
weigh_epochs(epochs, w_snr)
ev = epochs.average()
```

![image](https://cloud.githubusercontent.com/assets/4381290/19613414/41d51cec-97a1-11e6-8269-19e09ed52bbd.png)
Here the result of chpi weighted averaging (red) is overlayed on conventional averaging on a handful of channels. Question is whether (a) use of your code looks reasonable/correct? (b) do the results look reasonable - why do differences on some channels look like offsets? (c) what to do about the `ValueError` above?

**Comment by jjnurminen** [comment]
@kambysese 

a) Looks ok as far as I can tell :)

b) I'm wondering whether the reference data (yellow) was averaged with artifact rejection on? There might be some epochs with low-frequency artifact and the difference might come from the fact that rejection is turned off for the weighted averages.

c) The ValueError bug should be fixed now - the code didn't check for the case that there are no events corresponding to some (active) acquisition category. Please check out the latest commit at the meg_scripts repository.

**Comment by kambysese** [comment]
> b) I'm wondering whether the reference data (yellow) was averaged with artifact rejection on? There might be some epochs with low-frequency artifact and the difference might come from the fact that rejection is turned off for the weighted averages. (The rejection feature for the weighted averaging is almost done, but now I need to go abroad for a week, so it'll take a while more)

No, the yellow ERF was computed as:
```
epochs = mne.Epochs(raw_sss, events, event_id, tmin=-0.05, tmax=0.3,
                    proj=None, baseline=(None, 0),
                    reject=None, flat=None, preload=True)
```

That said, I am pretty confused about how the phantom triggers are organized, so there might be some discrepancy between how `ap.get_condition(raw_sss, ap['Dipole 7'], stim_channel='STI201')`
and `mne.find_events(raw_sss, stim_channel='STI201', consecutive = True, min_duration = 0.002, mask = 32 )` actually work.

**Comment by Eric89GXL** [comment]
It looks like `get_condition` will only return those from Dipole 7, whereas yours will get all 32 dipoles. So if you restrict your events to those with ID 7 like `events = events[events[:, 2] == 7]` then I imagine they'd be equivalent. But you can verify it with `assert np.array_equal(ap_events, fe_events)`

**Comment by jjnurminen** [comment]
`get_condition` returns whatever condition you give it.
However, iterating over `ap.categories` will only return categories that were marked active in the data acquisition. If you want to see all categories, check out `ap._categories`

Integration into mnefun coming in #154

**Comment by jjnurminen** [comment]
IIRC your phantom data has all 32 averaging categories active, but there are actual events only for category 7. I think this happens if you load the phantom averaging settings into DACQ, but only activate one dipole.

**Comment by larsoner** [comment]
Closing for PR
