### ISSUE TITLE
save_epochs raises error if all events rejected

### ISSUE THREAD

**Issue by ilogue** [LABSN/mnefun#139]
https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L1353

```
offset = max(epochs.events[:, 2].max(), new_numbers.max()) + 1
```

This line in `save_epochs` causes an error;

`zero-size array to reduction operation maximum which has no identity`;

 if the `epochs.events` array is empty, e.g. when all epochs were rejected.

**Comment by kambysese** [comment]
probably more useful if program exits with a warning if `epochs` has no data, WDYT @Eric89GXL

**Comment by Eric89GXL** [comment]
Yeah that would be good

**Comment by kambysese** [comment]
@ilogue you up to it? Or I can. Depends on how long you want to wait :)

**Comment by ilogue** [comment]
I'll give it a go. So don't continue with other subjects, just exit gracefully?

**Comment by kambysese** [comment]
Continuing with next subject is sensible, but I'm not sure that might be
more work than necessary. B/c at end of day params.subjects may need to
change to exclude subject.

-- 
Kambiz Tavabi
