### ISSUE TITLE
Projection vector "Average EEG reference"

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#140]
@Eric89GXL fu on 

> RuntimeWarning: Projection vector "Average EEG reference" has magnitude 0.12 (should be unity), applying projector with 53/60 of the original channels available may be dangerous, consider recomputing and adding projection vectors for channels that are eventually >used. If this is intentional, consider using info.normalize_proj() raw.apply_proj()

I still get this warning when `pre_bad.txt` & `post-sss.txt` files are identical. On a related note, is it the expected behavior that channels in the `pre_bad` end up in the `post-sss` file, i.e., are the pre-bad channels not excluded from the outset of processing?

**Comment by Eric89GXL** [comment]
The pre-bad MEG channels should *not* be marked bad in the SSS'ed file. SSS should reconstruct them.

We must be adding the avg eeg ref at the wrong time. We probably shouldn't add it on read, but rather read, add bads to info, then add avg eeg ref.

**Comment by kambysese** [comment]
We meaning mne-python or mnefun end? FYI I am hitting this on 2 of 29 datasets, so not sure if it's a corner case. 
Not understanding this. Why should SSS reconstruct bad channels? I was under the impression tsss operation spread bad channel data across sensors. Are you also implying that it is a bad idea to put channels (i.e., noisy channels that cause numerous trial drops) in the prebad list?

**Comment by Eric89GXL** [comment]
> Why should SSS reconstruct bad channels?

Any channels in `raw.info['bads']` when calling `maxwell_filter(raw, ...)` will simply be excluded during the multipole estimation step, but are easily reconstructed (and removed from `raw_sss.info['bads']`) from the multipole moments during the reconstruction step.

> I was under the impression tsss operation spread bad channel data across sensors

Yes, so you should mark any MEG channels that you know are pure noise or have jumpy artifacts in `raw_fif/subj_prebad.txt`. That is actually the only reason to have the prebad file.

> Are you also implying that it is a bad idea to put channels (i.e., noisy channels that cause numerous trial drops) in the prebad list?

There is no reason to put EEG data in the prebad list, for example. The only thing that prebad should be used for is excluding MEG channels from multipole moment estimation during SSS.

**Comment by Eric89GXL** [comment]
> We meaning mne-python or mnefun end?

mnefun

**Comment by kambysese** [comment]
I can't find where...

> We must be adding the avg eeg ref at the wrong time. We probably shouldn't add it on read, but rather read, add bads to info, then add avg eeg ref.

happens. Thought maybe [here](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L1814), or there bouts, but I'm really not sure. Any ideas?

**Comment by Eric89GXL** [comment]
The default behavior is to add on read

http://mne-tools.github.io/stable/generated/mne.io.read_raw_fif.html#mne.io.read_raw_fif

**Comment by kambysese** [comment]
fixed by #141
