### ISSUE TITLE
TypeError during anonymize

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#145]
@Eric89GXL Unable to find a quick fix for this, when `None` is used to anonymize

`[tuple([int(dd) for dd in d]) for d in np.array(dates)[sinds]]` at ln 517 in `do_processing` returns 
>TypeError: 'NoneType' object is not iterable

**Comment by Eric89GXL** [comment]
What branch are you on?

https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L517

**Comment by kambysese** [comment]
Nvmd :confounded:
