### ISSUE TITLE
Error reading post pca raw 

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#169]
@Eric89GXL 
Trace from TypeError related to opening `allclean_fil55_raw_sss.fif` file
> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/mnefun/examples/funloc/analysis_fun.py", line 134, in <module>
>     print_status=True,  # Print completeness status update
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 600, in do_processing
>     p.must_match, decim, run_indices)
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 1335, in save_epochs
>     raw = Raw(raw_fname, preload=False)
>   File "<string>", line 2, in __init__
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 707, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/fiff/raw.py", line 81, in __init__
>     preload, do_check_fname)
>   File "<string>", line 2, in _read_raw_file
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 707, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/fiff/raw.py", line 165, in _read_raw_file
>     duration = tag.data - onset
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by Eric89GXL** [comment]
You can't even read the file? Did it die while writing (e.g., ran out of disk space)?

**Comment by kambysese** [comment]
Died trying to read .../examples/funloc/subj_01/sss_pca_fif/subj_01_funloc_allclean_fil55_raw_sss.fif during epoching stage.

**Comment by Eric89GXL** [comment]
what is the size of the file? did you run out of disk space?

**Comment by kambysese** [comment]
The data is written (512MB for funloc example data, 1.6 GB for my own data) it's not a space issue. 
```
import mne
raw = mne.io.read_raw_fif('subj_01_erm_allclean_fil55_raw_sss.fif')
```

Gives same error. I can open and view files in mne_browse_raw.

**Comment by Eric89GXL** [comment]
That's really strange, because MNE wrote that file. Could you upload it to kasga so I can look?

**Comment by kambysese** [comment]
Placed projection and raw files for funloc subj_01 on KASGA at `data07/kam/for_eric/sss_pca_fif`

**Comment by Eric89GXL** [comment]
Closing as upstream bug
