### ISSUE TITLE
Write out data ndarrays

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#177]
@Eric89GXL WDYT about some sort of convenience function to write out compressed numpy ndarrays containing descriptive time/freq windowed data e.g., area under curve with shape obs x channels x time?

**Comment by Eric89GXL** [comment]
You can use h5io for such custom things

**Comment by kambysese** [comment]
what's the advantage over .npz?

**Comment by Eric89GXL** [comment]
If you want to write out list / dict / tuple / str and get those same types back `h5io` is better, if you want to store just numpy arrays `npz` is better

**Comment by kambysese** [comment]
For now I mostly use numpy ndarrays for containing/handling dependent measures; along the lines of the statistical analysis script example you gave me some time back. For wrangling data I've been messing around with pandas over dicts. So I think as a first pass I'll do `npz` and see if other use cases arise.
