### ISSUE TITLE
More informative error message

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#178]
Change assertion error message at [ln 651](https://github.com/LABSN/mnefun/blob/master/mnefun/_mnefun.py#L651).

**Comment by Eric89GXL** [comment]
Can you give a traceback?

**Comment by kambysese** [comment]
More of a note to self to create PR. It's a bit I did in the past; if e.g., no remote files are found during the fetching an assertion error is raised bc `remote_fnames` is empty.
