### ISSUE TITLE
PCA procedure

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#179]
@larsoner I noticed that even when all `params.proj_nums` are set to `[0, 0, 0]` it looks like `do_preprocessing_combined` still computes PCA. Is that normal/expected behavior?

**Comment by larsoner** [comment]
That sounds like a bug, do you have time to look into it?

**Comment by kambysese** [comment]
Sorry, not really at present. Just returning from vacation and not sure where to start.
