### ISSUE TITLE
Autoreject integration

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#182]
@larsoner I am thinking about integrating autoreject procedures into MNEFUN as soon as I understand what it's capable of and if it's worth doing. Here is what I am thinking:

1. one option is using `autoreject.get_rejection_threshold(epochs)` to compute channel thresholds during `save_epochs`
2. Alternatively, we could repair epochs [as per this](http://autoreject.github.io/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py)
One seems more straightforward but seems to be very slow. In both cases, I am not sure about how to handle projections. Right now I am trying this in `save_epochs`:

...
```
if p.auto_reject_threshold:  # PARAMS switch
    picks = pick_types(raw.info, eeg=True, meg=True, eog=False,
                                   exclude='bads')
    epochs = Epochs(raw, events, None, p.tmin, p.tmax, preload=True,
                                 baseline=_get_baseline(p), reject=None,
                                 flat=None, proj=True, picks=picks)  # quick and dirty epochs for autoreject
    new_dict = autoreject.get_rejection_threshold(epochs)
    for k in new_dict.keys():
        if k in p.reject.keys():
            p.reject[k] = new_dict[k]  # replace rejection criteria
```

WDYT?

**Comment by larsoner** [comment]
I don't have any experience using `autoreject` and don't have the time to drive that initiative right now. I would like to use it eventually, though, since it seems better than our current rejection stuff.

**Comment by kambysese** [comment]
Ok. Will close for now.
