### ISSUE TITLE
fir_design compatibility issue 

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#188]
@larsoner before updating to recent upstream today mne-python was complaining about:

> DeprecationWarning: fir_design defaults to "firwin2" in 0.15 but will change to "firwin" in 0.16, 
> set it explicitly to avoid this warning. =fir_window, **fir_kwargs)

With 0.15 update we getting

> File ".../mne-python/mne/filter.py", line 331, in _firwin_design
>     h[offset:N - offset] += this_h
> ValueError: operands could not be broadcast together with shapes (560,) (559,) (560,) 

We are using `fir_design='firwin2'` in `_raw_LRFCP. I am not actually sure why we're hitting this error with recent upstream?

looks like `_get_fir_kwargs` is misbehaving.

**Comment by larsoner** [comment]
I think this is a bug in MNE. Can you debug to figure out the parameters needed to use `create_filter` or `filter_data` to reproduce the same error? You probably need to know `fir_design, filter_length, phase, l_freq, h_freq, l_trans_bandwidth, h_trans_bandwidth`.

**Comment by ktavabi** [comment]
I can try to debug...
FYI I am getting two different `ValueErrors`
This (similar to original error) is what I am hitting with my own data:

>   Traceback (most recent call last):
>   File "/home/ktavabi/Projects/bad-baby/bad_baby/process_mismatch.py", line 125, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 625, in do_processing
>     outs[ii] = func(p, subjects, run_indices)
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 2083, in do_preprocessing_combined
>     **fir_kwargs)
>   File "<string>", line 2, in filter
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/base.py", line 1251, in filter
>     fir_window=fir_window, fir_design=fir_design, pad=pad)
>   File "<string>", line 2, in filter_data
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 862, in filter_data
>     h_trans_bandwidth, method, iir_params, phase, fir_window, fir_design)
>   File "<string>", line 2, in create_filter
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 1159, in create_filter
>     fir_window, fir_design)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 399, in _construct_fir_filter
>     h = fir_design(N, freq, gain, window=fir_window)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 331, in _firwin_design
>     h[offset:N - offset] += this_h
> ValueError: operands could not be broadcast together with shapes (64,) (63,) (64,) 

This is what I am hitting with funloc data:

> Traceback (most recent call last):
> Setting up low-pass filter at 55 Hz
>   File "/home/ktavabi/Projects/mnefun/examples/funloc/analysis_fun.py", line 137, in <module>
>     print_status=True,  # Print completeness status update
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 625, in do_processing
>     outs[ii] = func(p, subjects, run_indices)
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 2083, in do_preprocessing_combined
>     **fir_kwargs)
>   File "<string>", line 2, in filter
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/io/base.py", line 1251, in filter
>     fir_window=fir_window, fir_design=fir_design, pad=pad)
>   File "<string>", line 2, in filter_data
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 862, in filter_data
>     h_trans_bandwidth, method, iir_params, phase, fir_window, fir_design)
>   File "<string>", line 2, in create_filter
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 728, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 1159, in create_filter
>     fir_window, fir_design)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 399, in _construct_fir_filter
>     h = fir_design(N, freq, gain, window=fir_window)
>   File "/home/ktavabi/Projects/mne-python/mne/filter.py", line 323, in _firwin_design
>     % (N, transition * sfreq / 2., this_N))
> ValueError: The requested filter length 1024 is too short for the requested 0.25 Hz transition band, which requires 1241 samples

**Comment by ktavabi** [comment]
@larsoner Does [this](https://github.com/mne-tools/mne-python/issues/4693) make sense to you? Is it a bug?
