### ISSUE TITLE
BUG raw files with orig extension should be filtered

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#202]
`get_raw_fnames(p, subj, 'raw', erm=False, add_splits=True, indices=run_indices[si])` is returning raw files with .orig extension for reporting in #199. @larsoner I can't think of a reason these files should not be filtered out?  In my case files for .orig are being sent to KASGA for headpos estimation and causing remote errors. 

Perhaps modifying `_regex_convert(f)` to return `.*%s-?[0-9]*.fif(?!.orig) % op.basename(f)[:-4]`?

**Comment by larsoner** [comment]
We can just add the end-of-line char `$`

**Comment by larsoner** [comment]
Done in #199
