### ISSUE TITLE
Fix autoreject picks

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#206]
Restrict autoreject trial rejection criteria to MEEG channels only.

**Comment by larsoner** [comment]
We should probably make the default whatever the default is for `autoreject` (I assume this is M/EEG+EOG) but make it configurable if it's not too much work.

**Comment by ktavabi** [comment]
Yes that is the default but we don't do rejection on EOG - and I'm hitting cases where I'm losing excessive trials with computed EOG threshold. So I was thinking defaulting to just MEEG.

PS I  thought you were on vacation, I scheduled my down time around yours. Should I get back to the office?

**Comment by larsoner** [comment]
@mdclarke have you been using the `autoreject` option at all? If so is it okay if we change it to do just M/EEG by default? (If you wanted to keep using M/EEG + EOG you could do so via an argument.)

**Comment by mdclarke** [comment]
@larsoner I don't typically use autoreject, but I'm totally fine with the default being M/EEG and dropping EOG. Thanks for asking!

**Comment by larsoner** [comment]
@ktavabi do you have time to implement this?

**Comment by ktavabi** [comment]
Yes I can take care of this.
