### ISSUE TITLE
Declare subject

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#210]
@larsoner I am not exactly sure why this has worked up to now?! but this `stc.plot` call is using `stc.subject` as argument to `.plot` presumably inherited from `p.subjects`. I'm hitting an i/o error here b/c my `p.structurals` is a list of modified string-types e.g., `p.subjects = [sub-nbwr088]` `p.structurals = [sub-nbwr088_some-string]`. So I am wondering if we should explicitly set `subject` to `p.structurals[si]`?  

https://github.com/LABSN/mnefun/blob/b199c62a882a226f57a652c03ed4cd9e936a8845/mnefun/_report.py#L398

**Comment by larsoner** [comment]
>  I am not exactly sure why this has worked up to now?!

The `stc` is created on the fly using `apply_inverse`. The `inv` has `inv['src'][0]['subject_his_id']` which stores the structural used to create the inverse. This in turn gets stored in `stc.subject`. So it should always work. Can you check that your `p.structurals[si]` is the same as `inv['src'][0]['subject_his_id']`? I assume it's not, indicating that you need to regenerate forward and inverse.

**Comment by ktavabi** [comment]
`inv['src'][0]['subject_his_id']` is `sub-nbwr088` where as `p.structurals[si]` is  `sub-nbwr088_some-string`; which is what `struc` is set to. That doesn't necessarily clear things wrt to how this is working, but considering we use `struc = p.structurals[si]` throughout mnefun it maybe safer to use `struc` for all forward & inverse operations.

**Comment by larsoner** [comment]
> maybe safer to use struc for all forward & inverse operations.

The only place the user should need to set the Freesurfer subject name is in `p.structurals`. Somewhere along the line either 1) there is some MNE bug where this isn't saved / loaded properly in FIF, or 2) you changed `p.structurals` without also updating your forward + inv. If you load `fwd['src'][0]['subject_his_id']` you will probably also find that it is `' sub-nbwr088'`. If you want to use `sub-nbwr088_some-string` as your structural for these things, you'll need to regenerate forward and inverse.

We can add some sanity checks if you expect this to come up again, but AFAIK people usually set the structural once and never change it.

**Comment by ktavabi** [comment]
> We can add some sanity checks if you expect this to come up again, but AFAIK people usually set the structural once and never change it.
Your call. But chances are at this place it will come up as people move towards BIDS.
