### ISSUE TITLE
Unbounded local variable

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#211]
https://github.com/LABSN/mnefun/blob/b199c62a882a226f57a652c03ed4cd9e936a8845/mnefun/_report.py#L369
`inv_dir` accessed before assignment when data covariance file doesn't exist or user doesn't ask for whitened evoked butterfly i.e., `params.report_params.update(sensor=dict(analysis='All', name='All', times=[0.1, 0.2]))`

**Comment by larsoner** [comment]
Thanks, fix in #209
