### ISSUE TITLE
Needs Runtime exit with better error msg

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#216]
https://github.com/LABSN/mnefun/blob/3d28dad5a0d334a4ead848a15ff88904e5c4de85/mnefun/_report.py#L201
If SSP topomaps are requested or `proj` files do not exist this breaks with an unhelpful error message.
Need to improve error message and handling case where `proj` files are missing. 
@larsoner I'll do PR. Can you grant me permission for PR assignment?

**Comment by larsoner** [comment]
I added you as a collaborator, can you see if that works?
