### ISSUE TITLE
MAYAVI scenes cropped in report

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#217]
@larsoner zooming issue with MAYAVI figures in reports persists in newest mne `environment.yml` with  `hemi='split'` & `views='lat'` kwargs

![image](https://user-images.githubusercontent.com/4381290/38053746-bfa8d7d8-3289-11e8-8de1-54acb43e22ee.png)

**Comment by larsoner** [comment]
Is this on OSX or Linux?
