### ISSUE TITLE
missing transparent argument in _report.py

### ISSUE THREAD

**Issue by mdclarke** [LABSN/mnefun#219]
@larsoner I get this error when running gen_report:

  File "/home/meg/github/mnefun/mnefun/_report.py", line 414, in gen_html_report
    clim, stc_crop.data, 'viridis')[0]  # dummy cmap
TypeError: _limits_to_control_points() missing 1 required positional argument: 'transparent'

If I add a 'transparent' argument (such as below) to line 414 in _report.py  the error goes away:
https://github.com/LABSN/mnefun/blob/51ae8fe75fd6ddba8339ad9886b920e4a2f42049/mnefun/_report.py#L414
                        clim = mne.viz._3d._limits_to_control_points(
                             clim, stc_crop.data, 'viridis', **transparent=[0.2]**)[0]

**Comment by larsoner** [comment]
Should be fixed now!
