### ISSUE TITLE
MF autobad on ERM recordings

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#253]
@larsoner Is it necessary to run MF autobad on the ERM recordings or suffice to mark the same channels as bad in the actual recording? As is I suspect the resulting text file contains bad channels found in the ERM rather than datafile. https://github.com/LABSN/mnefun/blob/cc957a5b04a0340f2780eeeff99c4bf69c70c07a/mnefun/_mnefun.py#L1293

**Comment by larsoner** [comment]
> Is it necessary to run MF autobad on the ERM recordings or suffice to mark the same channels as bad in the actual recording?

The idea is that each run (experimental or empty room) should get the bad channels from:

1. <subject>_prebad.txt
2. <run>_maxbad.txt

>  I suspect the resulting text file contains bad channels found in the ERM rather than datafile.

There should end up being one _prebad.txt, and N_experiment+N_erm _maxbad.txt files. Is this not the case?

**Comment by ktavabi** [comment]
Right now we only get one _prebad.txt and n_erm_maxbad.txt files. Probably best to affix basename of `fif` file to the MF file, yes?

**Comment by larsoner** [comment]
That should already be what this line is doing

https://github.com/LABSN/mnefun/blob/cc957a5b04a0340f2780eeeff99c4bf69c70c07a/mnefun/_mnefun.py#L1295

**Comment by ktavabi** [comment]
I stand corrected. Sorry.
