### ISSUE TITLE
Standard error handling

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#254]
@larsoner I am hitting rare occasions where `subprocess` calls hang indefinitely presumably because the STDERR piping isn't working as expected i.e., printing error to screen. Any ideas how to improve this? https://github.com/LABSN/mnefun/blob/cc957a5b04a0340f2780eeeff99c4bf69c70c07a/mnefun/_mnefun.py#L2841

**Comment by larsoner** [comment]
Are you on latest MNE-Python? I pushed a fix for this sort of thing this week or last

**Comment by ktavabi** [comment]
:+1: No I don't have c2b917 merged. Thanks.
