### ISSUE TITLE
want_rank != out_rank

### ISSUE THREAD

**Issue by drammock** [LABSN/mnefun#263]
in the `generate_covariances` step, @nordme and I are hitting an `AssertionError` where `want_rank != out_rank`.  The one we just looked at was off by one, but I haven't yet looked at all the failing subjects (there are several) to confirm that it's always just a difference of one (which might suggest something as simple as a tolerance issue?).

I dug into it a little:

- `want_rank` -> `_mnefun.compute_rank` -> `mne.rank.estimate_rank` (with tolerance 1e-6) -> `_estimate_rank_from_s` (`s` comes from `scipy.linalg.svdvals`; rank = `sum(s > tolerance)`)
- `out_rank` -> `mne.cov.compute_whitener` -> `mne.cov.prepare_noise_cov` -> `_smart_eigh` (rank = `sum(eig > 0)`)

@larsoner what is your advice on how to fix / work around this issue?

**Comment by larsoner** [comment]
Can you upload a problematic subject with analysis script to kasga? I'll probably require some threshold tweaking, maybe a new parameter. Are there few epochs or something?

**Comment by nordme** [comment]
Hi Eric,

I'll upload data to your kasga incoming folder under /prek_out_rank_data

I'm not sure how many epochs qualifies as few, but there are 100 total: 30
epoch each for three main conditions and 10 epochs for a condition we're
not really analyzing (put in for subject entertainment, basically).

Thanks!

Erica Peterson
Research Scientist
Institute for Learning and Brain Sciences
University of Washington
Box 357988
Seattle, WA 98195
(206) 685-2842
