### ISSUE TITLE
add times='peaks' for source params in HTML reports

### ISSUE THREAD

**Issue by bonniekwlau** [LABSN/mnefun#281]
Can we add the option to enter times='peaks' for source params when generating HTML reports?

**Comment by larsoner** [comment]
@NeuroLaunch this might be a good first PR for `mnefun`. Basically

- a first iteration can look at `times` [here](https://github.com/LABSN/mnefun/blob/master/mnefun/_report.py#L672), and `if isinstance(times, str) and times == 'peaks':` create `times = ...` as an `ndarray` 
- you can use something like [scipy.signal.find_peaks](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html#scipy.signal.find_peaks) to figure out what the `times` array should contain
- it should probably operate on the GFP of the evoked data that will be source localized
- you can test and demonstrate on `funloc` data

Let me know if you're interested in / have the bandwidth for this, if not I can tackle it

**Comment by NeuroLaunch** [comment]
Once I get through this recent run-through of the MMF subjects I will have
time.  Thanks for asking.

**Comment by NeuroLaunch** [comment]
@larsoner, I think I have a fairly robust solution.  I am interpreting your suggestion above that it should work on the sensor-level GFP rather than across a source-level spatial average?  Also, presently I am providing times='peaks' functionality to the "source" section of a report, but I could also extend that to the "sensor" section (which also takes a times parameter).

**Comment by larsoner** [comment]
It would be good to provide support in both places

**Comment by NeuroLaunch** [comment]
This issue should be resolved now, @bonniekwlau.  Sensor and source report sections should use the same time slices for display (up to five) if both are set up with `times = 'peaks'`.

(I tried adding "closes LABSN#281" to one of the PR commits, hoping this Issue would close automatically with the merge; maybe that needs done in the main PR title/label.)
