### ISSUE TITLE
FIX: epoch processing of split raw files

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/mnefun#287]
I came across an error running `do_processing()` for epochs.  The traceback points to line 109 of __epoching.py_:

```
~/GitClones/mnefun/mnefun/_epoching.py in save_epochs(p, subjects, in_names, in_numbers, analyses, out_names, out_numbers, must_match, decim, run_indices)
    107 
    108         # read in events
--> 109         events = _read_events(p, subj, run_indices[si], raw)
    110         new_sfreq = raw.info['sfreq'] / decim[si]
    111         if p.disp_files:

~/GitClones/mnefun/mnefun/_scoring.py in _read_events(p, subj, ridx, raw)
    115                                % (fname,))
    116         events.append(these_events)
--> 117     events = concatenate_events(events, raw._first_samps, raw._last_samps)
    118     if len(np.unique(events[:, 0])) != len(events):
    119         raise RuntimeError('Non-unique event samples found after '

~/GitClones/mne-python/mne/event.py in concatenate_events(events, first_samps, last_samps)
    944     if not (len(events) == len(last_samps) and
    945             len(events) == len(first_samps)):
--> 946         raise ValueError('events, first_samps, and last_samps must all have '
    947                          'the same lengths')
    948     first_samps = np.array(first_samps)
```
A similar error occurs for __cov.py_ on line 135.

I believe the origin of the error is from the creation of a temporary raw objected concatenated across runs (e.g. at line 106 of __epoching_).  A test is made in `concatenate_events` to make sure the number of constituent events and raws match up, but the test fails because it's based on the raw attributes ._first_samps and ._last_samps, which indicate a concatenation even when only 1 run is being analyzed.

A related issue: In __epoching_ and __cov_, the variables `first_samps` and `last_samps` are created but never used.  I suspect they are part of vestigial code intended to bypass the edge case of split raw files.

I've written my _ad hoc_ own work-around for a F2F subject with split raw files, so I'd be happy to devise a permanent solution if @larsoner or someone concurs this is a genuine bug.

**Comment by larsoner** [comment]
Yes this sounds like a bug, feel free to open a PR to fix it

**Comment by NeuroLaunch** [comment]
I believe I solved the problem for __epoching_, but I can't complete my testing with __cov_ for what appears to be an unrelated reason.  Specifically, params.tmin, whose original value in this case was -1.0, gets rewritten to -0.9971051980889262.  This seems to happen somewhere in the mne-python function _epochs.py:__concatenate_epochs()_ around line 2897:
`baseline, tmin, tmax = out.baseline, out.tmin, out`
