### ISSUE TITLE
FIX: params.prebad error in print_status

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/mnefun#290]
When running do_processing() with print_status=True, the following error occurs:

`File "/Users/neuromac/GitClones/mnefun/mnefun/_status.py", line 45, in print_proc_status if subj in p.prebad or op.isfile(_prebad(p, subj)):  `
`AttributeError: 'Params' object has no attribute 'prebad'`

I think the relevant line should be `if subj in p.mf_prebad or op.isfile(_prebad(p, subj)):
            prebads = 'complete' ` to reflect the recent change in the .yml parameter setup.

**Comment by larsoner** [comment]
Argh yes I probably introduced some bug. Feel free to fix it if you're up for it
