### ISSUE TITLE
FIX: 'delayed' projectors option for epoching

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/mnefun#302]
The option for saving 'delayed' epochs projectors appears to be fixed in _epochs.py (line 151), rather than set by the relevant processing parameter.  More specifically, in an earlier update, `temp_epochs` (line 126) was defined with the argument `proj = params.epochs_proj`, however this epochs object is only for setting up threshold parameters for the autoreject module and is not saved to file.  Should `params.epochs_proj` actually be applied at line 151, where the final epochs are created?

**Comment by larsoner** [comment]
Argh yes it it should be on 151 but not in the `temp_epochs` 126 (this one should have them applied to help `autoreject` process properly), PR welcome to fix it

**Comment by NeuroLaunch** [comment]
Closed with #301
