### ISSUE TITLE
ENH: Provide more saving options for reports

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/mnefun#303]
It would be useful if reports of all processed subjects could optionally be placed into a single directory, following a specified string format, rather than the generic _work_dir/subj/'%s_fil%d_report.html_.  This could make it easier to keep track of multiple reports made for different purposes or at different times.  I've already experimented with my own mnefun branch to do this; I update `params.report_params` containing the new instructions just before evoking `mnefun.do_processing(params, gen_report=True)`.

I'd be happy to start a PR, but could use some advice re: how to properly prepare the parameters object.  Since `report_params.preload` is a new feature, perhaps we'd consider rolling it into a dictionary `report_params.options` along with the file-saving instructions (so that all non-section report instructions are in one place).

**Comment by larsoner** [comment]
To me this seems a little bit out of scope. Usually in `mnefun` each subject's data lands in their own folder. I think if you want some reorganization beyond that, a bash or Python script to `cp` or `ln` or whatever would be a better choice.

**Comment by NeuroLaunch** [comment]
OK - I'll probably just write a Python script to rename and move the reports (after renaming all existing reports before mnefun overwrites them).

**Comment by NeuroLaunch** [comment]
I found a good solution by leveraging the new "post-function" feature of mnefun's report generation.  The function backs up existing reports in subjects folders and writes a copy of the new report, with user-customized naming convention, into a designated user-named report folder.  So I'll close this Issue.
