### ISSUE TITLE
ImportError: 'spatial_src_connectivity'

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#314]
This an `import` conflict? @larsoner 

> _inverse.py in 
> ----> 7 from mne import (read_label, read_labels_from_annot, read_source_spaces, Label,
>       8                  SourceEstimate, BiHemiLabel, read_surface, read_epochs,
>       9                  read_cov, read_forward_solution, convert_forward_solution,..
>

**Comment by larsoner** [comment]
Should have been fixed in https://github.com/LABSN/mnefun/pull/308, are you up to date?

**Comment by ktavabi** [comment]
I'm in `git` limbo.
