### ISSUE TITLE
ENH: More event processing

### ISSUE THREAD

**Issue by larsoner** [LABSN/mnefun#319]
Here's a list of additional changes I hope you can make in this PR that will help my MNEFun code read in certain event files (that contain multiple event types sharing a timestamp).  The changes are pretty simple (a few lines in 3 files) and shouldn't impact greatly existing pipelines.  I think, in fact, that the change may be positive in that only epochs related to the targeted processing will be considered** when evaluating covariance and making epochs for calculating rejection criteria.

The main change is in _scoring.py at _read_events():
`def _read_events(p, subj, ridx, raw):`
becomes
`def _read_events(p, subj, ridx, raw, ids=None):`  at line 107
and
```
    for fname in get_event_fnames(p, subj, ridx):
        these_events = read_events(fname)
```
becomes
```
    for fname in get_event_fnames(p, subj, ridx):
        these_events = read_events(fname, include=ids)
```
  
Lines that call this function are in_epoching.py at line 105:
`        events = _read_events(p, subj, run_indices[si], raw, ids=in_numbers)`
 and in_cov.py at line 146:
`            events = _read_events(p, subj, ridx, raw, ids=p.in_numbers)`

**If you think it's best that _ids=params.in_numbers_ should be optional then perhaps a new parameter like `params.restrict_events = True` can be implemented, with the default set to _False_.

These modifications of course have nothing to do with the eSSS changes, so I'd be happy to put them in a different pull request if you'd like.  In any case, that's all the input I have for this PR for now.  I'll be using eSSS on upcoming processing and will get back to you if it causes unexpected problems.

_Originally posted by @NeuroLaunch in https://github.com/LABSN/mnefun/issues/317#issuecomment-761938280_

**Comment by larsoner** [comment]
> when evaluating covariance

At least for this we have `pick_events_cov`:

https://labsn.github.io/mnefun/overview.html#covariance-covariance-parameters

Have you seen/tried to use this?

We could do something similar for `pick_events_autoreject` or something. In general having a `callable` is a tiny bit nicer because it allows for more flexibility than just `ids` / array-of-int functionality.

**Comment by NeuroLaunch** [comment]
I haven't seen the pick_events_cov() function, but I'll check it out.  I can create a PR for this.
