### ISSUE TITLE
Legacy run

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#321]
`params.subjects = subjects[0]` string type breaks with...

> ~/Github/mnefun/mnefun/_mnefun.py in do_processing(p, fetch_raw, do_score, push_raw, do_sss, fetch_sss, do_ch_fix, gen_ssp, apply_ssp, write_epochs, gen_covs, gen_fwd, gen_inv, gen_report, print_status)
>     469         sinds = np.arange(len(p.subjects))
> --> 471     subjects = np.array(p.subjects)[sinds].tolist()
>     473     structurals = p.structurals
> IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

`params.subjects = [subjects[0]]` list type breaks with...

> ~/Github/mnefun/mnefun/_mnefun.py in do_processing(p, fetch_raw, do_score, push_raw, do_sss, fetch_sss, do_ch_fix, gen_ssp, apply_ssp, write_epochs, gen_covs, gen_fwd, gen_inv, gen_report, print_status)
>     473     structurals = p.structurals
>     474     if structurals is not None:
> --> 475         assert len(structurals) == n_subj_orig
>     476         structurals = np.array(structurals)[sinds].tolist()
> AssertionError:

**Comment by larsoner** [comment]
I think the supported use case is meant to be:
```
params.subjects = ['a', 'b']
params.structurals = ['a_match', 'b_match']
params.sinds = [0]
```
In other words, you don't modify `subjects` or `structurals`, they should always be [list of str](https://labsn.github.io/mnefun/overview.html#fetch-raw-raw-fetching-parameters) of the same length. PR welcome to update the docs if this is not clear.

AFAIK `subjects` as `str` and `len(structurals) != len(subjects)` wasn't meant to be a supported use case, but hopefully if it worked at one point it's not too bad to update your code to comply with the list-of-str approach.

**Comment by ktavabi** [comment]
If `sturcturals = null` in the YAML what's the point of this check? I'm not doing any PRs. I'll find a workaround.

**Comment by larsoner** [comment]
> If sturcturals = null in the YAML 

You should be able to do an equivalent of `params.structurals = None`. This should end up getting caught by this line in the code:
```
if structurals is not None:
```
I'm not sure why your value doesn't work properly since this seems to work:
```
>>> yaml.load('me: null', Loader=yaml.SafeLoader)
{'me': None}
```
Happy to work on a solution if you're still up for debugging, but if you just want to move on feel free
