### ISSUE TITLE
ENH: Cuda support

### ISSUE THREAD

**Issue by NeuroLaunch** [LABSN/mnefun#324]
I currently use these lines at the start of my mnefun pipeline scripts:
```
n_cores = os.cpu_count()
params.n_jobs = params.n_jobs_mkl = n_cores
params.n_jobs_fir = params.n_jobs_resample = n_cores
if mne.utils.get_config('MNE_USE_CUDA') == 'true':
    params.n_jobs_fir = params.n_jobs_resample = 'cuda'
```

... where 'cuda' is used for my Linux desktop but not my Mac laptop.  It would be nice if such settings could be initialized as defaults when `params` is created, either based on the _mne-python.json_ config file, like above, or comparable lines in the _mnefun.json_ config file.  Entries in _params.yml_ could still override the defaults.

Thoughts?  Is it better just to explicitly set all the n_jobs parameters for specific analyses?

**Comment by larsoner** [comment]
At this point I actually don't find much difference between CUDA and non-CUDA since filtering in SciPy is much faster nowadays. Have you checked? Maybe it's not worth pushing for supporting it if there aren't large gains anymore...

**Comment by NeuroLaunch** [comment]
I hadn't considered that.  Does the improved SciPy speed require the fast-Numpy package (I'm forgetting its actual name), or is this all standard now?

**Comment by larsoner** [comment]
Just plain SciPy version 1.4+ I think

**Comment by NeuroLaunch** [comment]
Closing.  I'll continue to set the various `n_jobs` programmatically, possibly taking the value from the machine-specific mnefun .json file.
