### ISSUE TITLE
fixed length trial events

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#329]
@larsoner: shouldn't this have something like `dur = 1` in case  `tmax` or `tmin` are NoneType?

[mnefun] mnefun/_ssp.py (Line 571)

```

    dur = p.tmax - p.tmin

```

[Open in IDE](https://api.codestream.com/c/YBtNEotjDWL9G1o4/3GFNCSMERbqjXfR_qxRzkQ?marker=603ebdbdc886590176405d59&ide=default&src=GitHub) · [Open on GitHub](https://github.com/labsn/mnefun/blob/e20d9c7a9c144821d7c57902baf2976779221c32/mnefun/_ssp.py#L571)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by larsoner** [comment]
Discussed in #330 so I'll close
