### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#331]
@larsoner: with these params effectively spanning two different files, how are they ever going to be accessed by introspection? 

[mnefun] mnefun/data/canonical.yml (Line 164)

```

  drop_log:

```

[Open in IDE](https://api.codestream.com/c/YBtNEotjDWL9G1o4/pO6RDA54RQGrMQrcsOt9fA?marker=6041f39e437f140175d759ef&ide=default&src=GitHub) · [Open on GitHub](https://github.com/labsn/mnefun/blob/fbd29652f7005ec876532d823966170ce1edd784/mnefun/data/canonical.yml#L164)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by larsoner** [comment]
> @larsoner: with these params effectively spanning two different files, how are they ever going to be accessed by introspection?

The YAML gets read and populates `params`, so in theory the `params` object should be introspect-able as it was before. Then if you wonder how a particular value got in `params`, it either got there from the YAML, the Python script, or from the defaults of the class. But if you can eliminate Python almost entirely like [we did for funloc](https://github.com/LABSN/mnefun/blob/master/examples/funloc/analysis_fun.py#L33-L37), then it effectively limits it to either being from YAML or from the defaults (or as always, maybe a bug in handling somewhere!).
