### ISSUE TITLE
TypeError: 'numpy.float64' object is not iterable

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#332]
@larsoner I'm curious to see if either you or Mark hit this error when setting times='peaks' during reporting.

> Traceback (most recent call last):
>   File “/home/ktavabi/Github/badbaby/badbaby/processing/run_mnefun.py”, line 161, in <module>
>     mnefun.do_processing(
>   File “/home/ktavabi/Github/mnefun/mnefun/_mnefun.py”, line 521, in do_processing
>     outs[ii] = func(p, subjects, structurals, run_indices)
>   File “/home/ktavabi/Github/mnefun/mnefun/_report.py”, line 868, in gen_html_report
>     times = _get_memo_times(
>   File “/home/ktavabi/Github/mnefun/mnefun/_report.py”, line 271, in _get_memo_times
>     memo[key] = _peak_times(evoked, cov)
>   File “/home/ktavabi/Github/mnefun/mnefun/_report.py”, line 306, in _peak_times
>     ‘,’.join(‘%0.3f’ % t for t in times),), end=‘’)
> TypeError: ‘numpy.float64’ object is not iterable

**Comment by larsoner** [comment]
Can you paste the full traceback of the error?

**Comment by ktavabi** [comment]
> Can you paste the full traceback of the error?

See above.

**Comment by drammock** [comment]
I don't see a traceback in the issue description.  All I see is the final `TypeError` in the issue title.
