### ISSUE TITLE
Depracation error

### ISSUE THREAD

**Issue by ktavabi** [LABSN/mnefun#341]
No `_get_hpi_info` in upstream

[mnefun] mnefun/_sss.py (Line 19)

```

from mne.chpi import read_head_pos, write_head_pos, filter_chpi, _get_hpi_info

```

[Open in IDE](https://api.codestream.com/c/YBtNEotjDWL9G1o4/Kb1FwBfMS-i6W0LulFKl_A?marker=6094eabfbef9a7058a289e0b&ide=default&src=GitHub) · [Open on GitHub](https://github.com/labsn/mnefun/blob/d0763288dbaa3aea8e6aa8cd341e24ee29e9a231/mnefun/_sss.py#L19)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by larsoner** [comment]
I should be able to fix early next week. In the meantime you could try adding a `try/except` to import, I don't think the API itself changed much

**Comment by ktavabi** [comment]
I thought `try/except` is the fix. How do you fix this?

**Comment by larsoner** [comment]
Yeah all I was going to do was `try/except` and any necessary argument name wrapping
