### ISSUE TITLE
epoching during cov computation fails because proj=False

### ISSUE THREAD

**Issue by drammock** [LABSN/mnefun#349]
I have a subject in the F2Fconn cohort (number 116) where epoching succeeds, but covariance computation fails, because during cov computation the Epochs constructor is called with a hardcoded `proj=False` ([here](https://github.com/LABSN/mnefun/blob/381823a9d26fdd189c4873f7ca1bed9c94f143d9/mnefun/_cov.py#L151)) and 100% of the epochs are getting rejected (267 of them survive if `proj=True`).  I have `epoching: autoreject_thresholds: True` in the config, and I think that means the values in `reject` will have been computed by `autoreject` *with the projectors active / applied* so they're really not appropriate to use when the projectors are turned off.

@NeuroLaunch @mdclarke did you run into this issue in your earlier work with this data?

@larsoner what is the logic behind using `proj=False` instead of `'delayed'` here?

**Comment by larsoner** [comment]
Just no logic / bad logic at work I think...

**Comment by NeuroLaunch** [comment]
I don't think I ran into that problem with subject 116, but this does seem like it might have affected all of my epoching (ECG rejection as well as affecting autoreject criteria).  In your respective opinions, is that worth my running through the last steps of the F2F (single-source, not correlation) spectral analysis?

**Comment by larsoner** [comment]
One question is whether it affects just baseline covariance (which I don't think f2f uses) or empty room (which I think it does?). Looking at the code and PR you can figure it out

**Comment by drammock** [comment]
it affects only baseline cov; empty room cov is computed with `compute_raw_covariance` (it is not epoched first)
