### ISSUE TITLE
Import error after updates

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#72]
@Eric89GXL `_simulate.py` is causing an ImportError because it cannot find `_bem_find_surface` in `mne.surface`. The most recent copy of mne.surface does not have a `_bem_find_surface` function that I can see. Perhaps this is a naming error that needs to be updated in mnefun?

**Comment by Eric89GXL** [comment]
Yeah I have that update locally but haven't pushed, will do tomorrow. Sorry
about that.
