### ISSUE TITLE
Additional remote sss options

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#76]
```python
opts = [['skip', '200 360'], ['hpicons']]  # input as list of [argument, parameter] pairs
# construct list of strings for appending to MF command
cmd = []
for opt in opts:
    if len(opt) == 2:
        cmd.append('{0}{1} {2}'.format('--', opt[0], opt[1]))
    else:
        cmd.append('{0}{1}'.format('--', opt[0]))
```
@Eric89GXL you okay with this approach for implementing user defined optional arguments for remote SSS?

**Comment by Eric89GXL** [comment]
I think the user-defined arguments should just be an arbitrary string that gets appended to the call. There are too many options for us to triage them properly in Python and Bash. So something like `params.mf_args = ''` by default and you can do e.g. `params.mf_args = '-skip 200 360` if you want that functionality. Then we need to document somewhere the fixed options that we already use, which I think include `hpicons`, `regularize`, etc.
