### ISSUE TITLE
ENH adding sensor space PLV function

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#85]
![image](https://cloud.githubusercontent.com/assets/4381290/9263676/ea2ce57a-41d3-11e5-90b2-c5d03ccffa96.png)

That is the result of a quick and dirty conversion of plv values across epochs courtesy of @rkmaddox into an evoked object, and plotted using `plot_topomap`. @Eric89GXL WDYT about adding this functionality to mnefun? And if you agree what are the recommendations about modifying the data in an evoked object from mne-python. For the above I just did

`evoked_fft.data=plv_data_array`
`evoked_fft.times=plv_frquency_bins`
`evoked_fft.plot_topomap(times=plv_frquency_bins, vmin=0, vmax=1, scale=1, scale_time=1, unit='PLV', time_format='%d Hz')`

**Comment by Eric89GXL** [comment]
I think it's a little bit specific to be part of the standard analysis stream. However, it's generally useful enough that we should probably add it *somewhere*. Maybe we should have `mnefun.analyses`, where this could be `plot_sensor_space_plv` or something?

**Comment by kambysese** [comment]
I agree.

**Comment by Eric89GXL** [comment]
Is the `anova_time` function somewhere in `mnefun`? If so, we should also move it to `mnefun.analyses`.

**Comment by kambysese** [comment]
I don't believe there is currently an `mnefun.analyses` so everything is under `mnefun`. And by `analyses` do you mean adding a `_analyses.py` file to the `mnefun` tree?

**Comment by Eric89GXL** [comment]
I was thinking `_analyses.py` file, yeah. I guess we can import the function into the `mnefun` namespace like everything else.
