### ISSUE TITLE
Source space geometry

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#95]
@Eric89GXL re:error message concerning the source space patch/distance info, I was able to resolve the issue by changing the `oct` argument in `mne.setup_srouce_space` from 6 to 5 to match the subdividing in the corresponding BEM. My guess is that the mapping operation from 10240 to 5120 triangles in a source space is not feasible; does that make sense? Can you explain. Also if this solution makes sense I can open a PR to make the `oct` kwarg open to user input. LMK.

**Comment by Eric89GXL** [comment]
Hmm, this really should succeed. Can you share the structural somewhere on soc? I wonder if there is a bug in mne-python that is causing this.

ico6 has 4098 vertices per hemisphere, ico5 is going to have quite a few less than that, so it would be better to get the 6 working. If we can't, I suppose we can make it a parameter.

**Comment by kambysese** [comment]
I tried reproducing this with the example data but was unable. 
You should know that this is infant data using a warped template MRI to create a minimal set of Freesurfer files, however `setup_source_space -oct 6 ` has worked in the past. I uploaded a subject's files onto soc share1/7-Brainteam/kam/Eric/kubi_td115

**Comment by kambysese** [comment]
@Eric89GXL you're not going to believe this. I reproduced this error with 'AKCLEE_110_slim' by (a) deleting any pre-existing source space file (2) changing the kwarg `n_jobs` from 6 to 18 (b/c why not?) in `mnefun.params` (3) run analysis.py with `gen_fwd=True` (4) change `n_jobs` back to 6 and error goes away. 
I didn't know what I was doing before, and I sure as hell don't know what I am doing now, please tell me you can replicate this.

**Comment by Eric89GXL** [comment]
I should be able to try it out tomorrow. This does suggest it's some bug with `mne-python`, there shouldn't be any difference in behavior (other than speed potentially) based on `n_jobs`.

**Comment by Eric89GXL** [comment]
Argh, didn't have time to do this today. Can it wait until late next week? Or is this preventing your analysis from proceeding?

**Comment by kambysese** [comment]
Well it's not preventing anything. But I will be able to sleep better if (a) I know it's an actual bug, and (b) that I will not have to retract the results I am seeing now because the source spaces are some how corrupt. 

There's been so much code tinkering for the infant data that it's beginning to be somewhat worrying I didn't stick to stable software versions. I should probably fall back to a virtual env with the stable release of mne-python and redo the analysis; but the clock is ticking on this data set; and I don't know how many issues will pop up in the use case of mnefun (current master) and the stable release of mne-python? Do you typically control software versions (i.e., sciypy, numpy, mne-python) for your studies?

**Comment by Eric89GXL** [comment]
Usually before publishing I'll re-run all the data analysis from scratch to make sure the results didn't change. I don't worry too much about mne-python because of how many regression tests it has. `mnefun` wasn't as rapidly developed / changed the last time I published, so I haven't worried too much about that. You can always reference a specific commit number if you need to, but I don't think you even need to publicize `mnefun`. You can just say you used mne-python of a specific version -- I think most labs have some custom scripts that go on top of main libraries, and that's the sort of function that `mnefun` serves. mne-python also plans to release by the end of the month, so you could presumably re-run your scripts with 0.10 once it comes out.

**Comment by Eric89GXL** [comment]
Thanks for recreating with `analysis_fun` that made it much easier to check and debug.

Any created/saved source spaces should be fine. This error occurred when n_jobs didn't evenly divide the number of source points, see mne-python PR. Feel free to reopen if it doesn't fix your issue.
