### ISSUE TITLE
dimension mismatch error during epoching

### ISSUE THREAD

**Issue by mdclarke** [LABSN/mnefun#97]
@Eric89GXL I'm using `mne0.9` + `mnefun` master along with up to date versions of Anaconda, Numpy, and Scipy. I am encountering:
ValueError: could not broadcast input array from shape (401,141) into shape (401,701) 
when epoching data for @kambysese. I was able to reproduce this error with the example funloc data. Apparently this error is occurring exclusively on my machine as both Kam and Myles were able to run `mne.Epoch` on the datasets in question in their environment.  We're hitting a dead end troubleshooting and wondering if you might have an idea what may be going on. Here I attach the traceback:

 File "/home/mdclarke/Documents/mnefun-master/examples/funloc/analysis_fun.py", line 114, in <module>
    print_status=True,  # Print completeness status update
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 501, in do_processing
    p.must_match, decim, run_indices)
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 1143, in save_epochs
    epochs.save(fif_file)
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mne/epochs.py", line 1427, in save
    data = self.get_data()
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mne/epochs.py", line 1173, in get_data
    data[ii] = self._preprocess(e.copy(), self.verbose)
ValueError: could not broadcast input array from shape (401,141) into shape (401,701)

**Comment by Eric89GXL** [comment]
Can you try latest `mne` master? A few bugs have been fixed since 0.9.

**Comment by mdclarke** [comment]
Do you mean switching over to the development version of mne?

**Comment by Eric89GXL** [comment]
Yeah, the latest `master` branch from here:

https://github.com/mne-tools/mne-python/

If you clone the repository to your machine, you can use `python setup.py develop` to install it, in which case whatever version you have checked out (`master`, `maint/0.9`, etc.) will be the currently active version on your machine, which is convenient.

**Comment by mdclarke** [comment]
We didn't think it might be related to `mne` as both Kam and Myles are on different versions. Out of curiosity in the future if I am not working in the `git` framework can I just update `mne` running `pip install --upgrade mne`?

**Comment by Eric89GXL** [comment]
You can upgrade that way, but it will only upgrade/do anything if a new version has been released. New versions are released every 6-12 months, so the upgrade schedule is slower than using `git`.

**Comment by mdclarke** [comment]
Thanks Eric!
